// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"cpru-api/ent/permission"
	"cpru-api/ent/predicate"
	"cpru-api/ent/user"
	"cpru-api/ent/userpermission"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserPermissionUpdate is the builder for updating UserPermission entities.
type UserPermissionUpdate struct {
	config
	hooks    []Hook
	mutation *UserPermissionMutation
}

// Where appends a list predicates to the UserPermissionUpdate builder.
func (upu *UserPermissionUpdate) Where(ps ...predicate.UserPermission) *UserPermissionUpdate {
	upu.mutation.Where(ps...)
	return upu
}

// SetUserID sets the "user_id" field.
func (upu *UserPermissionUpdate) SetUserID(i int) *UserPermissionUpdate {
	upu.mutation.SetUserID(i)
	return upu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (upu *UserPermissionUpdate) SetNillableUserID(i *int) *UserPermissionUpdate {
	if i != nil {
		upu.SetUserID(*i)
	}
	return upu
}

// SetPermissionID sets the "permission_id" field.
func (upu *UserPermissionUpdate) SetPermissionID(i int) *UserPermissionUpdate {
	upu.mutation.SetPermissionID(i)
	return upu
}

// SetNillablePermissionID sets the "permission_id" field if the given value is not nil.
func (upu *UserPermissionUpdate) SetNillablePermissionID(i *int) *UserPermissionUpdate {
	if i != nil {
		upu.SetPermissionID(*i)
	}
	return upu
}

// SetUser sets the "user" edge to the User entity.
func (upu *UserPermissionUpdate) SetUser(u *User) *UserPermissionUpdate {
	return upu.SetUserID(u.ID)
}

// SetPermission sets the "permission" edge to the Permission entity.
func (upu *UserPermissionUpdate) SetPermission(p *Permission) *UserPermissionUpdate {
	return upu.SetPermissionID(p.ID)
}

// Mutation returns the UserPermissionMutation object of the builder.
func (upu *UserPermissionUpdate) Mutation() *UserPermissionMutation {
	return upu.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (upu *UserPermissionUpdate) ClearUser() *UserPermissionUpdate {
	upu.mutation.ClearUser()
	return upu
}

// ClearPermission clears the "permission" edge to the Permission entity.
func (upu *UserPermissionUpdate) ClearPermission() *UserPermissionUpdate {
	upu.mutation.ClearPermission()
	return upu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (upu *UserPermissionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, upu.sqlSave, upu.mutation, upu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (upu *UserPermissionUpdate) SaveX(ctx context.Context) int {
	affected, err := upu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (upu *UserPermissionUpdate) Exec(ctx context.Context) error {
	_, err := upu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (upu *UserPermissionUpdate) ExecX(ctx context.Context) {
	if err := upu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (upu *UserPermissionUpdate) check() error {
	if upu.mutation.UserCleared() && len(upu.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserPermission.user"`)
	}
	if upu.mutation.PermissionCleared() && len(upu.mutation.PermissionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserPermission.permission"`)
	}
	return nil
}

func (upu *UserPermissionUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := upu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(userpermission.Table, userpermission.Columns, sqlgraph.NewFieldSpec(userpermission.FieldID, field.TypeInt))
	if ps := upu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if upu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userpermission.UserTable,
			Columns: []string{userpermission.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := upu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userpermission.UserTable,
			Columns: []string{userpermission.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if upu.mutation.PermissionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userpermission.PermissionTable,
			Columns: []string{userpermission.PermissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(permission.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := upu.mutation.PermissionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userpermission.PermissionTable,
			Columns: []string{userpermission.PermissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(permission.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, upu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userpermission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	upu.mutation.done = true
	return n, nil
}

// UserPermissionUpdateOne is the builder for updating a single UserPermission entity.
type UserPermissionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserPermissionMutation
}

// SetUserID sets the "user_id" field.
func (upuo *UserPermissionUpdateOne) SetUserID(i int) *UserPermissionUpdateOne {
	upuo.mutation.SetUserID(i)
	return upuo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (upuo *UserPermissionUpdateOne) SetNillableUserID(i *int) *UserPermissionUpdateOne {
	if i != nil {
		upuo.SetUserID(*i)
	}
	return upuo
}

// SetPermissionID sets the "permission_id" field.
func (upuo *UserPermissionUpdateOne) SetPermissionID(i int) *UserPermissionUpdateOne {
	upuo.mutation.SetPermissionID(i)
	return upuo
}

// SetNillablePermissionID sets the "permission_id" field if the given value is not nil.
func (upuo *UserPermissionUpdateOne) SetNillablePermissionID(i *int) *UserPermissionUpdateOne {
	if i != nil {
		upuo.SetPermissionID(*i)
	}
	return upuo
}

// SetUser sets the "user" edge to the User entity.
func (upuo *UserPermissionUpdateOne) SetUser(u *User) *UserPermissionUpdateOne {
	return upuo.SetUserID(u.ID)
}

// SetPermission sets the "permission" edge to the Permission entity.
func (upuo *UserPermissionUpdateOne) SetPermission(p *Permission) *UserPermissionUpdateOne {
	return upuo.SetPermissionID(p.ID)
}

// Mutation returns the UserPermissionMutation object of the builder.
func (upuo *UserPermissionUpdateOne) Mutation() *UserPermissionMutation {
	return upuo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (upuo *UserPermissionUpdateOne) ClearUser() *UserPermissionUpdateOne {
	upuo.mutation.ClearUser()
	return upuo
}

// ClearPermission clears the "permission" edge to the Permission entity.
func (upuo *UserPermissionUpdateOne) ClearPermission() *UserPermissionUpdateOne {
	upuo.mutation.ClearPermission()
	return upuo
}

// Where appends a list predicates to the UserPermissionUpdate builder.
func (upuo *UserPermissionUpdateOne) Where(ps ...predicate.UserPermission) *UserPermissionUpdateOne {
	upuo.mutation.Where(ps...)
	return upuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (upuo *UserPermissionUpdateOne) Select(field string, fields ...string) *UserPermissionUpdateOne {
	upuo.fields = append([]string{field}, fields...)
	return upuo
}

// Save executes the query and returns the updated UserPermission entity.
func (upuo *UserPermissionUpdateOne) Save(ctx context.Context) (*UserPermission, error) {
	return withHooks(ctx, upuo.sqlSave, upuo.mutation, upuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (upuo *UserPermissionUpdateOne) SaveX(ctx context.Context) *UserPermission {
	node, err := upuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (upuo *UserPermissionUpdateOne) Exec(ctx context.Context) error {
	_, err := upuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (upuo *UserPermissionUpdateOne) ExecX(ctx context.Context) {
	if err := upuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (upuo *UserPermissionUpdateOne) check() error {
	if upuo.mutation.UserCleared() && len(upuo.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserPermission.user"`)
	}
	if upuo.mutation.PermissionCleared() && len(upuo.mutation.PermissionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserPermission.permission"`)
	}
	return nil
}

func (upuo *UserPermissionUpdateOne) sqlSave(ctx context.Context) (_node *UserPermission, err error) {
	if err := upuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userpermission.Table, userpermission.Columns, sqlgraph.NewFieldSpec(userpermission.FieldID, field.TypeInt))
	id, ok := upuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserPermission.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := upuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userpermission.FieldID)
		for _, f := range fields {
			if !userpermission.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userpermission.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := upuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if upuo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userpermission.UserTable,
			Columns: []string{userpermission.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := upuo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userpermission.UserTable,
			Columns: []string{userpermission.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if upuo.mutation.PermissionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userpermission.PermissionTable,
			Columns: []string{userpermission.PermissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(permission.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := upuo.mutation.PermissionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userpermission.PermissionTable,
			Columns: []string{userpermission.PermissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(permission.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserPermission{config: upuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, upuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userpermission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	upuo.mutation.done = true
	return _node, nil
}
