// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cpru-api/ent/permission"
	"cpru-api/ent/user"
	"cpru-api/ent/userpermission"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// UserPermission is the model entity for the UserPermission schema.
type UserPermission struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// FK ไปยัง user
	UserID int `json:"user_id,omitempty"`
	// FK ไปยัง permission
	PermissionID int `json:"permission_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserPermissionQuery when eager-loading is set.
	Edges        UserPermissionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserPermissionEdges holds the relations/edges for other nodes in the graph.
type UserPermissionEdges struct {
	// ความสัมพันธ์กับ user
	User *User `json:"user,omitempty"`
	// ความสัมพันธ์กับ permission
	Permission *Permission `json:"permission,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserPermissionEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// PermissionOrErr returns the Permission value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserPermissionEdges) PermissionOrErr() (*Permission, error) {
	if e.Permission != nil {
		return e.Permission, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: permission.Label}
	}
	return nil, &NotLoadedError{edge: "permission"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserPermission) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case userpermission.FieldID, userpermission.FieldUserID, userpermission.FieldPermissionID:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserPermission fields.
func (up *UserPermission) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case userpermission.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			up.ID = int(value.Int64)
		case userpermission.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				up.UserID = int(value.Int64)
			}
		case userpermission.FieldPermissionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field permission_id", values[i])
			} else if value.Valid {
				up.PermissionID = int(value.Int64)
			}
		default:
			up.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserPermission.
// This includes values selected through modifiers, order, etc.
func (up *UserPermission) Value(name string) (ent.Value, error) {
	return up.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the UserPermission entity.
func (up *UserPermission) QueryUser() *UserQuery {
	return NewUserPermissionClient(up.config).QueryUser(up)
}

// QueryPermission queries the "permission" edge of the UserPermission entity.
func (up *UserPermission) QueryPermission() *PermissionQuery {
	return NewUserPermissionClient(up.config).QueryPermission(up)
}

// Update returns a builder for updating this UserPermission.
// Note that you need to call UserPermission.Unwrap() before calling this method if this UserPermission
// was returned from a transaction, and the transaction was committed or rolled back.
func (up *UserPermission) Update() *UserPermissionUpdateOne {
	return NewUserPermissionClient(up.config).UpdateOne(up)
}

// Unwrap unwraps the UserPermission entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (up *UserPermission) Unwrap() *UserPermission {
	_tx, ok := up.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserPermission is not a transactional entity")
	}
	up.config.driver = _tx.drv
	return up
}

// String implements the fmt.Stringer.
func (up *UserPermission) String() string {
	var builder strings.Builder
	builder.WriteString("UserPermission(")
	builder.WriteString(fmt.Sprintf("id=%v, ", up.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", up.UserID))
	builder.WriteString(", ")
	builder.WriteString("permission_id=")
	builder.WriteString(fmt.Sprintf("%v", up.PermissionID))
	builder.WriteByte(')')
	return builder.String()
}

// UserPermissions is a parsable slice of UserPermission.
type UserPermissions []*UserPermission
